name = "portfolio"
account_id = "8da4d3d2a433962e4bba9d3cc26bf686"
compatibility_date = "2024-04-03"

[ai]
binding = "AI"

[assets]
directory = "./dist"

[vars]
OWNER_NAME = "Ashfaq ur Rahman"
TO_EMAIL = "urrahmanmohammadashfaq@gmail.com"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "75f6221e15ef407eb6460f2c9878b431"
preview_id = "75f6221e15ef407eb6460f2c9878b431"

[[kv_namespaces]]
binding = "SESSION"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "b2a7c764-7910-4ff4-986e-132b5d8d34b9"

# Durable Objects removed for now — add later
# [[durable_objects.bindings]]
# name = "CONTACT_RATE_LIMITER"
# class_name = "RateLimiter"
# script_name = "portfolio-rate-limiter"

# [[migrations]]
# tag = "v1"
# new_sqlite_classes = ["RateLimiter"]

[observability]
enabled = true